### ISSUE TITLE
test_model.py

### ISSUE THREAD

**Issue by yilawu** [aiff22/PyNET-PyTorch#9]
I want to recover a raw image using the pretrained model.
However, it reports that

Traceback (most recent call last):
  File "D:\Anaconda3\envs\torch\lib\site-packages\PIL\TiffImagePlugin.py", line 1238, in _setup
    self.mode, rawmode = OPEN_INFO[key]
KeyError: (b'II', 32803, (1,), 1, (16,), ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/pycharmPrograms/PyNET_aiff22/test_model.py", line 92, in <module>
    test_model()
  File "F:/pycharmPrograms/PyNET_aiff22/test_model.py", line 69, in test_model
    raw_image = next(visual_iter)
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "F:\pycharmPrograms\PyNET_aiff22\load_data.py", line 91, in __getitem__
    raw_image = np.asarray(imageio.imread(os.path.join(self.raw_dir, self.test_images[idx])))
  File "D:\Anaconda3\envs\torch\lib\site-packages\imageio\core\functions.py", line 221, in imread
    reader = read(uri, format, "i", **kwargs)
  File "D:\Anaconda3\envs\torch\lib\site-packages\imageio\core\functions.py", line 143, in get_reader
    return format.get_reader(request)
  File "D:\Anaconda3\envs\torch\lib\site-packages\imageio\core\format.py", line 164, in get_reader
    return self.Reader(self, request)
  File "D:\Anaconda3\envs\torch\lib\site-packages\imageio\core\format.py", line 214, in __init__
    self._open(**self.request.kwargs.copy())
  File "D:\Anaconda3\envs\torch\lib\site-packages\imageio\plugins\pillow.py", line 127, in _open
    self._im = factory(self._fp, "")
  File "D:\Anaconda3\envs\torch\lib\site-packages\PIL\ImageFile.py", line 103, in __init__
    self._open()
  File "D:\Anaconda3\envs\torch\lib\site-packages\PIL\TiffImagePlugin.py", line 1001, in _open
    self._seek(0)
  File "D:\Anaconda3\envs\torch\lib\site-packages\PIL\TiffImagePlugin.py", line 1056, in _seek
    self._setup()
  File "D:\Anaconda3\envs\torch\lib\site-packages\PIL\TiffImagePlugin.py", line 1242, in _setup
    raise SyntaxError("unknown pixel mode")
SyntaxError: unknown pixel mode

I put my dng pic into the folder  raw_images/test/huawei_full_resolution.
And my dng pic was photoed by HONOR V30 pro.

**Comment by aiff22** [comment]
@wurongyuan, can you please attach your sample DNG files so that we can reproduce this issue?

**Comment by yilawu** [comment]
> @wurongyuan, can you please attach your sample DNG files so that we can reproduce this issue?
.dng pic is not supported uploading

**Comment by yilawu** [comment]
> > @wurongyuan, can you please attach your sample DNG files so that we can reproduce this issue?
> > .dng pic is not supported uploading

can you leave you email?

**Comment by aiff22** [comment]
@wurongyuan, please use the first email from the paper.
